/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ui.VentanasEmergentes;

<<<<<<< HEAD
import Dao.FacultadDao;
import Dao.PersonaDao;
import java.util.List;
import tecnologiasavanzadas.practicapoo.Facultad;
import tecnologiasavanzadas.practicapoo.Persona;
=======
import Controlador.FacultadControlador;
import Controlador.PersonaControlador;
import DTO.PersonaDTO;
import java.util.List;

>>>>>>> f076d41 (Version-4)

/**
 *
 * @author jsdvp
 */
public class FormularioFacultad extends javax.swing.JDialog {

    /**
     * Creates new form FormularioFacultad
     */
<<<<<<< HEAD
    
    List<Persona> decanos;
    
    
    public FormularioFacultad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
=======
    private final PersonaControlador personaControlador;
    private final FacultadControlador facultadControlador;
    List<PersonaDTO> decanos;
    
    
    public FormularioFacultad(java.awt.Frame parent, boolean modal, PersonaControlador personaControlador, FacultadControlador facultadControlador) {
        super(parent, modal);
        this.personaControlador = personaControlador;
        this.facultadControlador = facultadControlador;
>>>>>>> f076d41 (Version-4)
        initComponents();
        cargarDecanosEnComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreFacultad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_crear = new javax.swing.JButton();
        comboDecanos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Decano");

        jLabel2.setText("Nombre");

        jLabel1.setText("Nueva Facultad");

        btn_crear.setText("Crear");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        comboDecanos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(nombreFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_crear, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addComponent(comboDecanos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nombreFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboDecanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btn_crear)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarDecanosEnComboBox() {
<<<<<<< HEAD
        PersonaDao personaDao = new PersonaDao();
        decanos = personaDao.leerPersonas();
        
        comboDecanos.removeAllItems();

        // Agregar los decanos al ComboBox
        for (Persona decano : decanos) {
=======
        decanos = personaControlador.obtenerPersonas();
        comboDecanos.removeAllItems();

        for (PersonaDTO decano : decanos) {
>>>>>>> f076d41 (Version-4)
            comboDecanos.addItem(decano.getNombre());
        }
    }
    
    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
<<<<<<< HEAD
        
        FacultadDao facultadDao = new FacultadDao();
        
        int selectedIndex = comboDecanos.getSelectedIndex();
        Persona selectedDecano = null;
=======
     
        int selectedIndex = comboDecanos.getSelectedIndex();
        PersonaDTO selectedDecano = null;
>>>>>>> f076d41 (Version-4)

        if (selectedIndex != -1) {
            selectedDecano = decanos.get(selectedIndex);
            String nombreFacultadNueva  = nombreFacultad.getText();
<<<<<<< HEAD
            
            Facultad facultad = new Facultad(nombreFacultadNueva, selectedDecano);
            
            facultadDao.crearFacultad(facultad);
=======
           
            facultadControlador.crearFacultad(nombreFacultadNueva, selectedDecano.getId());
>>>>>>> f076d41 (Version-4)
        }
        
        this.dispose();
    }//GEN-LAST:event_btn_crearActionPerformed

    /**
     * @param args the command line arguments
     */
<<<<<<< HEAD
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioFacultad dialog = new FormularioFacultad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

=======
>>>>>>> f076d41 (Version-4)
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crear;
    private javax.swing.JComboBox<String> comboDecanos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombreFacultad;
    // End of variables declaration//GEN-END:variables
}
