/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui;
<<<<<<< HEAD
import Dao.PersonaDao;
=======
import Controlador.PersonaControlador;
import DTO.PersonaDTO;
>>>>>>> f076d41 (Version-4)
import Ui.VentanasEmergentes.FormularioDecano;
import Ui.VentanasEmergentes.FormularioDecanoActualizar;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
<<<<<<< HEAD
import tecnologiasavanzadas.practicapoo.Persona;
=======

>>>>>>> f076d41 (Version-4)

/**
 *
 * @author jsdvp
 */
public class TablaDecano extends javax.swing.JPanel {

    /**
     * Creates new form FormularioDecano
     */
<<<<<<< HEAD
    public TablaDecano() {
        initComponents();
=======
    
    private final PersonaControlador personaControlador;
    
    public TablaDecano(PersonaControlador personaControlador) {
        initComponents();
        this.personaControlador = personaControlador;
>>>>>>> f076d41 (Version-4)
        refrescar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borrar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btn_crear = new javax.swing.JButton();

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Decanos");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
        }

        btn_crear.setText("Crear");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_crear)
                                .addGap(18, 18, 18)
                                .addComponent(actualizar)
                                .addGap(18, 18, 18)
                                .addComponent(borrar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crear)
                    .addComponent(actualizar)
                    .addComponent(borrar))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private Double idSeleccionado(){
        int selectedRow = tabla.getSelectedRow();
        Double idSeleccionado = null;

        if (selectedRow != -1) {
            idSeleccionado = (Double) tabla.getValueAt(selectedRow, 0);
        }   
        
        return idSeleccionado;
    }
    
    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
       
       
<<<<<<< HEAD
        FormularioDecanoActualizar formularioDecanoActualizar = new FormularioDecanoActualizar((JFrame) SwingUtilities.getWindowAncestor(this), true);
=======
        FormularioDecanoActualizar formularioDecanoActualizar = new FormularioDecanoActualizar((JFrame) SwingUtilities.getWindowAncestor(this), true, personaControlador);
>>>>>>> f076d41 (Version-4)
        
        formularioDecanoActualizar.setId(idSeleccionado());
        
        formularioDecanoActualizar.setVisible(true);
        
        refrescar();
    }//GEN-LAST:event_actualizarActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
<<<<<<< HEAD
        FormularioDecano formularioDecano = new FormularioDecano((JFrame) SwingUtilities.getWindowAncestor(this), true);
=======
        FormularioDecano formularioDecano = new FormularioDecano((JFrame) SwingUtilities.getWindowAncestor(this), true, personaControlador);
>>>>>>> f076d41 (Version-4)
        
        formularioDecano.setVisible(true);
        
        refrescar();
    }//GEN-LAST:event_btn_crearActionPerformed

    
    public void refrescar(){
<<<<<<< HEAD
        PersonaDao personaDao = new PersonaDao();
        
        List<Persona> personas = personaDao.leerPersonas();

        DefaultTableModel model = new DefaultTableModel();

       
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Email");

        for (Persona persona : personas) {
            model.addRow(new Object[]{
                persona.getId(),
                persona.getNombre(),
                persona.getApellido(),
                persona.getEmail()
            });
        }

        tabla.setModel(model);
    }        
    
    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        PersonaDao personaDao = new PersonaDao();
        
        personaDao.eliminarPersona(idSeleccionado());    
=======
        List<PersonaDTO> facultades = personaControlador.obtenerPersonas();
        
        DefaultTableModel model =  (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);

        for (PersonaDTO dto : facultades) {
            model.addRow(new Object[]{ dto.getId(), dto.getNombre(), dto.getApellido(), dto.getEmail()  });
        }
    }        
    
    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        personaControlador.eliminarPersona(idSeleccionado());    
>>>>>>> f076d41 (Version-4)
        
        refrescar();
    }//GEN-LAST:event_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton borrar;
    private javax.swing.JButton btn_crear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
