/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui;
import Dao.FacultadDao;
import Ui.VentanasEmergentes.FormularioFacultad;
import Ui.VentanasEmergentes.FormularioFacultadActualizar;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import tecnologiasavanzadas.practicapoo.Facultad;


/**
 *
 * @author jsdvp
 */
public class TablaFacultad extends javax.swing.JPanel {

    /**
     * Creates new form FormularioFacultad
     */
    public TablaFacultad() {
        initComponents();
        refrescar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borrar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btn_crear = new javax.swing.JButton();

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Facultades");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Decano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        btn_crear.setText("Crear");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_crear)
                                .addGap(18, 18, 18)
                                .addComponent(actualizar)
                                .addGap(18, 18, 18)
                                .addComponent(borrar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crear)
                    .addComponent(actualizar)
                    .addComponent(borrar))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void refrescar(){
        FacultadDao facultadDao = new FacultadDao();
        
        List<Facultad> facultades = facultadDao.leerFacultades();

        DefaultTableModel model = new DefaultTableModel();

       
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Decano");
        

        for (Facultad facultad : facultades) {
            model.addRow(new Object[]{
                facultad.getId(),
                facultad.getNombre(),
                facultad.getDecano().getNombre() + " " + facultad.getDecano().getApellido(),
            });
        }

        tabla.setModel(model);
    }        
    
    private Double idSeleccionado(){
        int selectedRow = tabla.getSelectedRow();
        Double idSeleccionado = null;

        if (selectedRow != -1) {
            idSeleccionado = (Double) tabla.getValueAt(selectedRow, 0);
        }   
        
        return idSeleccionado;
    }
    
    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        FormularioFacultadActualizar formularioFacultadActualizar = new FormularioFacultadActualizar((JFrame) SwingUtilities.getWindowAncestor(this), true);
        
        formularioFacultadActualizar.setId(idSeleccionado());
        
        formularioFacultadActualizar.setVisible(true);
        
        refrescar();
    }//GEN-LAST:event_actualizarActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        FormularioFacultad formularioFacultad = new FormularioFacultad((JFrame) SwingUtilities.getWindowAncestor(this), true);
        
        formularioFacultad.setVisible(true);
        
        refrescar();
    }//GEN-LAST:event_btn_crearActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        FacultadDao facultadDao = new FacultadDao();
        
        facultadDao.eliminarFacultad(idSeleccionado());
        
        refrescar();
    }//GEN-LAST:event_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton borrar;
    private javax.swing.JButton btn_crear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
